options = optimoptions('ga', ...
'MutationFcn', {@mutationadaptfeasible, 0.25}, ...
'CrossoverFcn', @crossoverintermediate, ...
'PopulationSize', 50, ...
'MaxGenerations', 150, ...
'EliteCount', 2, ...
'SelectionFCN', @selectionroulette, ...
'FitnessScalingFcn', @fitscalingprop, ...
'PlotFcn','gaplotbestf');

problem = struct('fitnessfcn', @fitnessVal, 'nvars', 3, 'options', options);
ga(problem); 
